// ═══════════════════════════════════════
// Session config
// ═══════════════════════════════════════

export type DemoStep = "prep" | "live" | "report";

export type InterviewLanguage = "fr" | "en" | "es" | "pt" | "zh";

export interface SessionConfig {
  language: InterviewLanguage;
  jobDescription: string;
  candidateName: string;
  techStack?: string;
  questions?: GeneratedQuestion[];
  scorecard?: ScorecardCriterion[];
}

// ═══════════════════════════════════════
// Questions & Scorecard (generated by AI)
// ═══════════════════════════════════════

export interface GeneratedQuestion {
  id: string;
  text: string;
  category: "TECHNICAL" | "SYSTEM_DESIGN" | "BEHAVIORAL" | "CULTURE_FIT";
  difficulty: "EASY" | "MEDIUM" | "HARD";
  expectedAnswer: string;
  isAsked: boolean;
}

export interface ScorecardCriterion {
  id: string;
  name: string;
  description: string;
  weight: number; // 1-3
  score: number | null; // 1-5 or null
  notes: string | null;
}

export interface JobAnalysis {
  summary: string;
  criticalSkills: { name: string; why: string }[];
  niceToHave: string[];
  questions: GeneratedQuestion[];
  scorecard: ScorecardCriterion[];
}

// ═══════════════════════════════════════
// Tech Translation (live)
// ═══════════════════════════════════════

export interface TechTranslation {
  term: string;
  definition: string;
  relatedTechs: string[];
  criticality: "HIGH" | "MEDIUM" | "LOW";
}

// ═══════════════════════════════════════
// Transcript
// ═══════════════════════════════════════

export interface TranscriptEntry {
  id: string;
  text: string;
  timestamp: number;
}

// ═══════════════════════════════════════
// Report (post-call)
// ═══════════════════════════════════════

export interface InterviewReport {
  summary: string;
  strengths: string[];
  weaknesses: string[];
  redFlags: string[];
  recommendation: "STRONG_HIRE" | "HIRE" | "LEAN_HIRE" | "LEAN_NO_HIRE" | "NO_HIRE";
  overallScore: number; // 1-5
  scoredCriteria: ScorecardCriterion[];
}

// ═══════════════════════════════════════
// WebSocket messages
// ═══════════════════════════════════════

export type ClientMessage =
  | { type: "session:start"; config: SessionConfig }
  | { type: "session:stop" }
  | { type: "audio:chunk"; data: string }
  | { type: "question:mark-asked"; questionId: string }
  | { type: "criterion:score"; criterionId: string; score: number }
  | { type: "ping" };

export type ServerMessage =
  | { type: "session:ready"; sessionId: string }
  | { type: "session:error"; error: string }
  | { type: "transcript:partial"; text: string }
  | { type: "transcript:final"; text: string }
  | { type: "tech:translation"; translation: TechTranslation }
  | { type: "assist:start" }
  | { type: "assist:chunk"; text: string }
  | { type: "assist:done"; fullText: string }
  | { type: "assist:error"; error: string }
  | { type: "pong" };

// ═══════════════════════════════════════
// Constants
// ═══════════════════════════════════════

export const AUDIO_SAMPLE_RATE = 16000;
export const AUDIO_CHANNELS = 1;
export const AUDIO_CHUNK_MS = 250;
export const WS_PING_INTERVAL_MS = 30000;
export const DEBOUNCE_MS = 1800;

export function createId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}
